version: '3.2'
services:
  php:
    image: serversideup/php:8.2-fpm-nginx
    depends_on:
      - db
    ports:
      - 2080:80
    volumes:
      - ./:/var/www/html
    environment:
      PUID: 1000
      PGID: 1000
      COMPOSER_HOME: /var/www/.composer
      PHP_POOL_NAME: "dev"
      PHP_DATE_TIMEZONE: "Europe/Bucharest"
      PHP_PM_CONTROL: "dynamic"
      PHP_PM_MAX_CHILDREN: "5"
      PHP_PM_START_SERVERS: "2"
      PHP_POST_MAX_SIZE: "1024M"
      PHP_UPLOAD_MAX_FILESIZE: "1024M"
      AUTORUN_LARAVEL_STORAGE_LINK: false
      SSL_MODE: off
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
  
  
  db:
    image: mariadb:11
    #image: mysql
    #image: percona/percona-server:8.0
    ports:
      - 23306:3306
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - 23456:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
  
